# Generated by Django 4.1.1 on 2023-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaptopModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mname", models.CharField(max_length=25)),
                ("mprice", models.IntegerField()),
                ("mqty", models.IntegerField()),
            ],
        ),
    ]
