# Generated by Django 4.0.7 on 2022-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_category', models.CharField(max_length=25)),
                ('cloth_price', models.FloatField()),
                ('cloth_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MensModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_category', models.CharField(max_length=25)),
                ('cloth_price', models.FloatField()),
                ('cloth_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WomenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_category', models.CharField(max_length=25)),
                ('cloth_price', models.FloatField()),
                ('cloth_qty', models.IntegerField()),
            ],
        ),
    ]
