# Generated by Django 4.1.1 on 2023-07-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DevDetailsModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("join_date", models.DateField()),
            ],
        ),
    ]
