# Generated by Django 4.1.1 on 2023-07-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CopperDetailsModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prd_reg_no", models.IntegerField()),
                ("prd_name", models.CharField(max_length=25)),
                ("prd_qty", models.IntegerField()),
                ("prd_price", models.IntegerField()),
            ],
        ),
    ]
