# Generated by Django 4.1.1 on 2023-08-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamsModelDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("age", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("city", models.CharField(max_length=25)),
            ],
        ),
    ]
