# Generated by Django 4.0.7 on 2022-10-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_type', models.CharField(max_length=20)),
                ('shoes_price', models.FloatField()),
                ('shoes_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SlipperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slipper_type', models.CharField(max_length=20)),
                ('slipper_price', models.FloatField()),
                ('slipper_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_shoes_type', models.CharField(max_length=20)),
                ('sports_shoes_price', models.FloatField()),
                ('sports_shoes_qty', models.IntegerField()),
            ],
        ),
    ]
